esphome:
  name: wheatgrass-sensors
  friendly_name: wheatgrass sensors

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Wheatgrass-Sensors"
    password: !secret ap_password

captive_portal:
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  # ---- BME280 (0x76)
  - platform: bme280_i2c
    address: 0x76
    i2c_id: bus_a
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    pressure:
      name: "Pressure"
    update_interval: 0.5s

# ---- Light Sensor TSL2591
  - platform: tsl2591
    name: "TSL2591"
    i2c_id: bus_a      # use the same I2C bus you defined above
    update_interval: 0.5s
    gain: auto         # optional, but usually a good default

    calculated_lux:
      name: "Light"
      device_class: illuminance
      state_class: measurement
      unit_of_measurement: lx
